module.exports = {
  apps: [
    {
      name: 'backend',
      script: 'venv/bin/uvicorn',
      args: 'app.main:app --host 0.0.0.0 --port 8000',
      cwd: '/home/ThePredMain/backend',
      interpreter: 'python3',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        PYTHONPATH: '.',
        POSTGRES_HOST: 'localhost',
        POSTGRES_PORT: 5432,
        POSTGRES_DB: 'thepred',
        POSTGRES_USER: 'thepred',
        POSTGRES_PASSWORD: 'SUPER_STRONG_PASSWORD_CHANGE_ME_123!@#',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
        JWT_SECRET: 'YOUR_SUPER_SECRET_JWT_KEY_MINIMUM_32_CHARS_RANDOM',
        JWT_ALGORITHM: 'HS256',
        JWT_EXPIRE_HOURS: 24,
        DEBUG: 'false',
        INITIAL_PRED_BALANCE: 10000,
        REFERRAL_BONUS_PRED: 1000,
        S3_ENDPOINT: 'http://localhost:9000',
        S3_ACCESS_KEY: 'admin',
        S3_SECRET_KEY: 'Ivanbunin110818',
        S3_BUCKET: 'thepred-events',
        S3_PUBLIC_URL: 'https://thepred.store',
      },
    },
    {
      name: 'webapp',
      script: 'main.py',
      cwd: '/home/ThePredMain/webapp',
      interpreter: 'venv/bin/python3',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        PYTHONPATH: '.',
        API_URL: 'http://localhost:8000',
        WEBAPP_URL: 'https://thepred.tech',
        WEBAPP_SECRET_KEY: 'WEBAPP_SECRET_KEY_RANDOM_STRING_32_CHARS',
        DEV_MODE: 'false',
        BOT_TOKEN: '8067436515:AAGHg6_ojgsnBmREI1U9Sr_iibgXYGInml0',
        BOT_USERNAME: 'The_Pred_Bot',
        S3_PUBLIC_URL: 'https://thepred.store',
        S3_BUCKET: 'thepred-events',
      },
    },
    {
      name: 'admin',
      script: 'main.py',
      cwd: '/home/ThePredMain/admin',
      interpreter: 'venv/bin/python3',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        PYTHONPATH: '.',
        API_URL: 'http://localhost:8000',
        ADMIN_PASSWORD: 'STRONG_ADMIN_PASSWORD_CHANGE_ME',
        ADMIN_SECRET_KEY: 'ADMIN_SECRET_KEY_RANDOM_32_CHARS',
        S3_PUBLIC_URL: 'https://thepred.store',
        S3_BUCKET: 'thepred-events',
      },
    },
    {
      name: 'bot',
      script: 'main.py',
      cwd: '/home/ThePredMain/bot',
      interpreter: 'venv/bin/python3',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        PYTHONPATH: '.',
        BOT_TOKEN: '8067436515:AAGHg6_ojgsnBmREI1U9Sr_iibgXYGInml0',
        API_URL: 'http://localhost:8000',
        WEBAPP_URL: 'https://thepred.tech',
      },
    },
    {
      name: 'landing',
      script: 'main.py',
      cwd: '/home/ThePredMain/landing',
      interpreter: 'venv/bin/python3',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        PYTHONPATH: '.',
      },
    },
  ],
};
